development:
  dialect: postgres
  datasource: postgres://root:123456@localhost:33062/seacloudapp?sslmode=disable
  dir: migrations
  table: gorp_migrations

test:
  dialect: postgresql
  datasource: root:root@tcp(127.0.0.1:33062)/seacloudtest?parseTime=true
  dir: migrations
  table: gorp_migrations
