name: Database Deployment

on:
  push:
    branches:
      - database

jobs:
  make_db:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate env file
        run: echo "${{ secrets.ENV_FILE_DB }}" >> .env

      - name: Copy Tools and env file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP_DB }}
          username: ${{ secrets.VM_USER_DB }}
          key: ${{ secrets.SSH_KEY_DB }}
          source: |
            .env
            tools/compose
          target: '~'
          recursive: true

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_DB }}
          username: ${{ secrets.VM_USER_DB }}
          key: ${{ secrets.SSH_KEY_DB }}
          script: |
            cd ~/tools/compose
            docker-compose --env-file ~/.env -f docker-compose.yml down
            docker-compose --env-file ~/.env -f docker-compose.yml up -d
