name: Golang App Deployment

on:
  push:
    branches:
      - main
      - github-workflow
      - database
      - seed-admin
      - migrate
      - thumbnail

env:
  IMAGE_NAME: seacloudserver/app

jobs:
  make_db:
    if: github.ref == 'refs/heads/database'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate env file
        run: echo "${{ secrets.ENV_FILE_DB }}" >> .env

      - name: SCP env file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP_DB }}
          username: ${{ secrets.VM_USER_DB }}
          key: ${{ secrets.SSH_KEY_DB }}
          source: '.env'
          target: '~'

      - name: SCP Tools to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP_DB }}
          username: ${{ secrets.VM_USER_DB }}
          key: ${{ secrets.SSH_KEY_DB }}
          source: 'tools/compose'
          target: '~'
          recursive: true

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_DB }}
          username: ${{ secrets.VM_USER_DB }}
          key: ${{ secrets.SSH_KEY_DB }}
          script: |
            cd ~/tools/compose
            docker-compose --env-file ~/.env -f docker-compose.yml down
            docker-compose --env-file ~/.env -f docker-compose.yml up -d
            rm ~/.env
            rm -rf ~/tools

  seed_admin:
    if: github.ref == 'refs/heads/seed-admin'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        run: |
          repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$repository_lowercase/seed-admin -f cmd/seed/Dockerfile .
          docker push ghcr.io/$repository_lowercase/seed-admin

      - name: Seed Admin Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            echo "${{ secrets.ENV_FILE }}" >> .env
            scp .env ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:~/
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/$repository_lowercase/seed-admin
            
            # Check if the container exists
            if docker ps -a --format '{{.Names}}' | grep -Eq "^seed-admin$"; then
              docker stop seed-admin
              docker rm seed-admin
            fi
            
            docker run -d --name seed-admin --env-file ~/.env ghcr.io/$repository_lowercase/seed-admin
            rm ~/.env

  migrate:
    if: github.ref == 'refs/heads/migrate'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        run: |
          repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$repository_lowercase/migrate -f cmd/migrate/Dockerfile .
          docker push ghcr.io/$repository_lowercase/migrate

      - name: Migrate Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            echo "${{ secrets.ENV_FILE }}" >> .env
            scp .env ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:~/
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/$repository_lowercase/migrate
            
            # Check if the container exists
            if docker ps -a --format '{{.Names}}' | grep -Eq "^migrate$"; then
              docker stop migrate
              docker rm migrate
            fi
            
            docker run -d --name migrate --env-file ~/.env ghcr.io/$repository_lowercase/migrate
            rm ~/.env

  thumbnail:
    if: github.ref == 'refs/heads/thumbnail'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        run: |
          repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$repository_lowercase/thumbnail -f cmd/thumbnail/Dockerfile .
          docker push ghcr.io/$repository_lowercase/thumbnail

      - name: Thumbnail Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            echo "${{ secrets.ENV_FILE }}" >> .env
            scp .env ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:~/
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/$repository_lowercase/thumbnail
            
            # Check if the container exists
            if docker ps -a --format '{{.Names}}' | grep -Eq "^thumbnail"; then
              docker stop thumbnail
              docker rm thumbnail
            fi
            
            docker run -d --name thumbnail --env-file ~/.env ghcr.io/$repository_lowercase/thumbnail
            rm ~/.env

  make_app:
    if: github.ref == 'refs/heads/github-workflow' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        run: |
          repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$repository_lowercase -f cmd/httpserver/Dockerfile .
          docker push ghcr.io/$repository_lowercase

  deploy:
    if: github.ref == 'refs/heads/github-workflow' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    needs: [make_app]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate env file
        run: echo "${{ secrets.ENV_FILE }}" >> .env

      - name: SCP env to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            .env
            docker-compose.yml
          target: '~'

      - name: SCP docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.yml'
          target: '~'

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            docker pull ghcr.io/$repository_lowercase
            docker tag ghcr.io/$repository_lowercase ${{ env.IMAGE_NAME }}
            docker rmi ghcr.io/$repository_lowercase
            
            cd ~
            docker compose --env-file ~/.env -f docker-compose.yml down
            docker compose --env-file ~/.env -f docker-compose.yml up -d

            docker image prune -f
            rm ~/.env ~/docker-compose.yml
